### ISSUE TITLE
A small todo-list for when I come back

### ISSUE THREAD

**Issue by slumpsand** [slumpsand/mining#2]
- [ ] make the bottom camera offset dependent on the screen size
- [ ] rewrite the clamp camera position method
- [ ] continue the worker stuff
- [ ] I think not enough tiles are generated (background, both height and width)
- [ ] check that the grass has a height of one unit
- [ ] repair the `NewBehaviourScript.txt` file
